PROTOCOL_ALREADY_EXISTS = "Protocol '{protocol_name}' already exists in project '{project_name}'."
PROTOCOL_DOES_NOT_EXIST = "Protocol '{protocol_name}' doesn't exist in project '{project_name}'."
PROTOCOL_IS_LOCKED = "Protocol '{protocol_name}' in project '{project_name}' is locked."
ACTIVITY_INVALID_FILE_PATH = "Invalid file path for activity '{activity_name}' in protocol '{protocol_name}'."
ACTIVITY_INVALID_TIME_LIMIT = "Invalid time limit for activity '{activity_name}' in protocol '{protocol_name}'."
ACTIVITY_PROCESS_NAME_REQUIRED = "Process name is required for activity '{activity_name}' in protocol '{protocol_name}'."