import os

from mo.core.config.constants import APP_DATA_DIR, RELATIVE_APP_DATA_PATH

PROJECTS_DIR_NAME = "projects"
PROJECTS_DATA_FILE_NAME = "projects.json"
RELATIVE_PROJECTS_PATH = os.path.join(RELATIVE_APP_DATA_PATH, PROJECTS_DIR_NAME)
PROJECTS_PATH = os.path.join(APP_DATA_DIR, RELATIVE_PROJECTS_PATH)
PARTICIPANTS_DATA_FILE_NAME = "participants.json"
PROTOCOLS_DATA_FILE_NAME = "protocols.json"
