sonar.projectKey=mo_ui
sonar.projectName=mo_ui
sonar.projectVersion=0.1.0
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**,**/out/**,**/resources/**,**/plugins-dev/**
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.coverage.exclusions=src/**