sonar.projectKey=mo_api
sonar.projectName=mo_api
sonar.projectVersion=0.1.0
sonar.python.version=3.12
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.exclusions=**/tests/**,**/venv/**,**/__pycache__/**,**/scripts/**
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/schemas/**,**/routers/**,**/utils/**,**/errors/**,**/main.py,**/exceptions.py